[package]
name = "section12-test"
version = "0.1.0"
authors = ["Jordi Estap√© <jestape@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
